// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2' // Versión compatible con Gradle 8.9
        classpath 'com.google.gms:google-services:4.4.0' // Asegúrate de actualizar si es necesario
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.10" // Compatible con Java 17 y AGP 8.7.2
    }
}

apply from: "variables.gradle"

ext {
    compileSdkVersion = 34 // Define estas variables globales
    minSdkVersion = 22
    targetSdkVersion = 34
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

