# sonar-project.properties
sonar.projectKey=parking
sonar.projectName=parking
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://192.168.1.9:9000
sonar.login=sqp_fe2646f23e631f7cf77cb17327567c34a670b85c